### PR TITLE
Add support for osx-arm64 using cross toolchains

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge/help-osx-arm64 I've been able to cross compile, but I don't have a machine to test it. Could someone from the team having access to the new hardware test these changes? For convenience, I'm attaching a local build.
[orjson-3.4.7-py39h8d19ad6_0.tar.bz2.zip](https://github.com/conda-forge/orjson-feedstock/files/5863885/orjson-3.4.7-py39h8d19ad6_0.tar.bz2.zip)

**Comment by isuruf** [comment]
```
% conda build --test orjson-3.4.7-py39h8d19ad6_0.tar.bz2
TEST START: orjson-3.4.7-py39h8d19ad6_0.tar.bz2
Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
WARNING:conda_build.build:Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/isuruf/miniforge3/conda-bld/orjson_1611545073739/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


The following NEW packages will be INSTALLED:

    ca-certificates: 2020.12.5-h4653dfc_0     conda-forge
    certifi:         2020.12.5-py39h2804cbe_1 conda-forge
    libcxx:          11.0.1-h168391b_0        conda-forge
    ncurses:         6.2-h9aa5885_4           conda-forge
    openssl:         1.1.1i-h27ca646_0        conda-forge
    orjson:          3.4.7-py39h8d19ad6_0     local      
    pip:             21.0-pyhd8ed1ab_0        conda-forge
    python:          3.9.1-hcbd9b3a_3_cpython conda-forge
    python_abi:      3.9-1_cp39               conda-forge
    readline:        8.0-hc8eb9b7_2           conda-forge
    setuptools:      49.6.0-py39h2804cbe_3    conda-forge
    sqlite:          3.34.0-h6d56c25_0        conda-forge
    tk:              8.6.10-hf7e6567_1        conda-forge
    tzdata:          2020f-he74cb21_0         conda-forge
    wheel:           0.36.2-pyhd3deb0d_0      conda-forge
    xz:              5.2.5-h642e427_1         conda-forge
    zlib:            1.2.11-h31e879b_1009     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/Users/isuruf/miniforge3/conda-bld/orjson_1611545073739/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export SRC_DIR=/Users/isuruf/miniforge3/conda-bld/orjson_1611545073739/test_tmp
import: 'orjson'
import: 'orjson'

Resource usage statistics from testing orjson:
   Process count: 2
   CPU time: Sys=0:00:00.0, User=0:00:00.0
   Memory: 12.3M
   Disk usage: 24B
   Time elapsed: 0:00:02.0


TEST END: orjson-3.4.7-py39h8d19ad6_0.tar.bz2
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO conda_build.config:__exit__(805): --dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

All tests passed


####################################################################################
Source and build intermediates have been left in /Users/isuruf/miniforge3/conda-bld.
There are currently 1 accumulated.
To remove them, you can run the ```conda build purge``` command
```

**Review by isuruf — CHANGES_REQUESTED** [review]
If you use `{{ compiler('rust') }}` all of this should be set for you

**Comment by nehaljwani** [comment]
Thank you for testing, @isuruf !

Orjson folks almost always use bleeding edge features which are only available in nightly releases of rust/cargo at the time of release. I am explicitly turning on one right now in the recipe for correctly parsing Cargo.toml.

If there is a provision to use nightly builds with `{{ compiler ('rust') }}`, I'd be happy to switch.

**Comment by isuruf** [comment]
We build nightlies at https://github.com/conda-forge/rust-feedstock/tree/dev. (Not automatically, so it needs to be bumped)

**Comment by nehaljwani** [comment]
I am merging this for now. Created an issue to track the switch at https://github.com/conda-forge/orjson-feedstock/issues/33

**Pull request merged**
