### PR TITLE
Fix hanging ppc64le  build and add janjagusch as maintainer

### PR DESCRIPTION
**Pull request by janjagusch**
I would like to help keep the recipe up-to-date.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by janjagusch** [comment]
git push --set-upstream origin add-janjagusch-as-recipe-maintainer

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Comment by janjagusch** [comment]
@conda-forge-admin, please rerender

**Comment by janjagusch** [comment]
> This PR seems to be going beyond the scope of its original intention. If there's something specific you want to help with, I think it would be open to open a PR to address that issue specifically. We're currently looking into an issue with ppc64le builds that's blocking some PRs.

Sorry for the noise, @synapticarbors. I'm trying to fix the blocking builds. I've changed the PR back into a draft, so you won't get notified while I'm debugging against CI.

**Comment by xhochy** [comment]
@janjagusch If this passes, you need to update the build no still.

**Comment by janjagusch** [comment]
> @janjagusch If this passes, you need to update the build no still.

Done, thanks @xhochy. 🙏

**Pull request closed without merging**
